<div class="container">

  <div class="row height d-flex justify-content-center align-items-center">

    <div class="col-md-8">
      <form action="/index/search" method="POST">
        <div class="form">
          <i class="fa fa-search"></i>
          <input type="text" class="form-control form-input" placeholder="Search anything...">
          <span class="left"><input type="submit"></span>
        </div>

    </div>
    </form>
  </div>

</div>